document.write("<div class='wrapper'><div id='topbutton'><a href='#'><i class='fas fa-arrow-circle-up'></i></a></div>");
document.write("<div class='header container-fluid d-flex justify-content-center'><img src='images/logo.jpg' alt='Logo' class='logo' width='100px'></div>"
    + "<nav class='navbar navbar-expand-lg navbar-light bg-light' id='nav'>"
    + "<a class='navbar-brand' href='index.html'>Zarmaan</a>"
    + "<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>"
    + "<span class='navbar-toggler-icon'></span>"
    + "</button>"
    + "<div class='collapse navbar-collapse' id='navbarSupportedContent'>"
    + "<ul class='navbar-nav mr-auto'>"
    + "<li class='nav-item active'>"
    + "<a class='nav-link' href='index.html'>Home <span class='sr-only'>(current)</span></a>"
    // + "</li>"
    // + "<li class='nav-item dropdown'>"
    // + "<a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>Products</a>"
    // + "<div class='dropdown-menu' aria-labelledby='navbarDropdown'>"
    // + "<a class='nav-link' href=''>Earphones/Handsfree</a>"
    // + "<a class='nav-link' href=''>Chargers</a>"
    // + "<ul class='navbar-nav mr-auto'>"
    // + "<li class='nav-item dropdown'>"
    // + "<a class='nav-link dropdown-toggle' href='' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>USB Cables</a>"
    // + "<div class='dropdown-menu' aria-labelledby='navbarDropdown'>"
    // + "<a class='nav-link' href''>Type C</a>"
    // + "<a class='nav-link' href''>Micro USB</a>"
    // + "</div>"
    // + "</li>"
    // + "</ul>"
    // + "</div>"
    // + "</li>"
    + "<li class='nav-item'>"
    + "<a class='nav-link' href='about.html'>About Us</a>"
    + "</li>"
    + "<li>"
    + "<a class='nav-link' href='feedback.html'>Feedback</a>"
    + "</li>"
    + "</ul>"
    + "<form class='form-inline my-2 my-lg-0'>"
    // + "<input class='form-control mr-sm-2' type='search' placeholder='Search' aria-label='Search'>"
    // + "<button class='btn btn-outline-success my-2 my-sm-0' type='submit'>Search</button>"
    + "</form>"
    + "</div>"
    + "</nav>");